// Harness Specification Template
// This template is used to generate harness-compatible spec files from eLuma ideas

import { HarnessExportInput } from '../types';

export const generateHarnessTemplate = (input: HarnessExportInput): string => {
  const techStackTable = Object.entries(input.techStack)
    .filter(([_, value]) => value && value.trim())
    .map(([key, value]) => `| ${capitalizeFirst(key)} | ${value} |`)
    .join('\n');

  return `# ${input.projectName} - Harness Specification

<!--
  GENERATED BY eLuma Companion
  ============================

  This specification was auto-generated from an eLuma idea capture.
  The features below were expanded by AI from ${input.mainFeatures.length} main features.

  KATEGORIEN → MODELLE:
  - config, test         → Haiku (einfach, 5-10 turns)
  - database, api, ui    → Sonnet (mittel, 10-25 turns)
  - integration, security → Opus (komplex, 25-50 turns)
-->

## Projekt-Übersicht

**Ziel:** ${input.problemStatement}

**Typ:** ${input.projectType}

**Zielgruppe:** ${input.targetAudience}

**MVP-Scope:** ${input.solution}

---

## Tech-Stack

| Komponente | Technologie |
|------------|-------------|
${techStackTable}

---

## Architektur

\`\`\`
┌─────────────┐     ┌─────────────┐     ┌─────────────┐
│   Frontend  │────▶│   Backend   │────▶│  Database   │
│ (${input.techStack.frontend || 'TBD'}) │     │ (${input.techStack.backend || 'TBD'}) │     │ (${input.techStack.database || 'TBD'}) │
└─────────────┘     └─────────────┘     └─────────────┘
       │                   │
       │                   ▼
       │            ┌─────────────┐
       └───────────▶│    Auth     │
                    │ (${input.techStack.auth || 'TBD'}) │
                    └─────────────┘
\`\`\`

**Patterns:**
- Repository Pattern für Database-Zugriff
- Service Layer für Business-Logik
- REST API mit OpenAPI 3.0 Spec
- Row Level Security für Multi-Tenancy

**Konventionen:**
- Naming: camelCase (Variablen), PascalCase (Komponenten)
- Files: kebab-case
- API: \`/api/v1/\` Prefix
- Errors: \`{ error: string, code: string, details?: object }\`

---

## Constraints & Differenzierung

**Constraints:**
${input.constraints}

**Differenzierung:**
${input.differentiation}

**Bekannte Risiken:**
${input.risks}

**Nächste Schritte:**
${input.nextSteps}

---

# FEATURES

<!--
  FEATURE-FORMAT:

  ### [KATEGORIE]-[NUMMER]: [Titel]
  **Kategorie:** [config|database|service|api|ui|integration|security|test|worker]
  **Komplexität:** [simple|medium|complex]
  **Abhängig von:** [Feature-IDs, kommasepariert]

  - [ ] Akzeptanzkriterium 1
  - [ ] Akzeptanzkriterium 2
  - [ ] Akzeptanzkriterium 3
-->

## Eingabe-Features vom User

Die folgenden ${input.mainFeatures.length} Hauptfeatures wurden vom User definiert:

${input.mainFeatures.map((f, i) => `${i + 1}. ${f}`).join('\n')}

---

## Phase 1: Foundation (Priority 1)

### CONFIG-001: Project Setup
**Kategorie:** config | **Komplexität:** simple

- [ ] package.json mit allen Dependencies
- [ ] TypeScript Konfiguration (tsconfig.json)
- [ ] ESLint + Prettier Setup
- [ ] Git-Hooks mit Husky
- [ ] .gitignore für ${input.techStack.backend?.includes('Node') ? 'Node.js' : 'generische'} Projekte

### CONFIG-002: Environment Setup
**Kategorie:** config | **Komplexität:** simple
**Abhängig von:** CONFIG-001

- [ ] .env.example mit allen Variablen
- [ ] .env.local für lokale Entwicklung
- [ ] Environment-Validierung beim Start
- [ ] Dokumentation der Variablen

### CONFIG-003: Database Connection
**Kategorie:** config | **Komplexität:** simple
**Abhängig von:** CONFIG-002

- [ ] ${input.techStack.database} Client initialisiert
- [ ] Connection Pooling konfiguriert
- [ ] Health-Check Endpoint \`/api/health\`
- [ ] Retry-Logik bei Connection-Fehlern

---

## Phase 2: Database (Priority 1-2)

### DATABASE-001: Core Schema
**Kategorie:** database | **Komplexität:** medium
**Abhängig von:** CONFIG-003

- [ ] Users Tabelle (id, email, name, avatar_url, created_at, updated_at)
- [ ] Profiles Tabelle (user_id FK, settings JSONB)
- [ ] Timestamps automatisch (trigger)
- [ ] Soft-Delete mit deleted_at

### DATABASE-002: Main Entity Schema
**Kategorie:** database | **Komplexität:** medium
**Abhängig von:** DATABASE-001

- [ ] Hauptentität Tabelle mit allen Feldern
- [ ] Foreign Keys zu Users
- [ ] Indexes für häufige Queries
- [ ] Check Constraints für Validierung

### DATABASE-003: Migrations System
**Kategorie:** database | **Komplexität:** simple
**Abhängig von:** DATABASE-001

- [ ] ${input.techStack.database} Migrations Ordner-Struktur
- [ ] Initial Migration für alle Tabellen
- [ ] Seed-Daten für Entwicklung
- [ ] README mit Migration-Anleitung

---

## Phase 3: Backend Services (Priority 2)

### SERVICE-001: User Registration
**Kategorie:** service | **Komplexität:** medium
**Abhängig von:** DATABASE-001

- [ ] POST /api/auth/register Endpoint
- [ ] Email-Format Validierung
- [ ] Password-Stärke Check (min 8 chars)
- [ ] ${input.techStack.auth} Integration
- [ ] Welcome-Email (optional)

### SERVICE-002: User Login
**Kategorie:** service | **Komplexität:** medium
**Abhängig von:** SERVICE-001

- [ ] POST /api/auth/login Endpoint
- [ ] JWT Token via ${input.techStack.auth}
- [ ] Refresh Token Handling
- [ ] Rate Limiting (5 Versuche/Minute)
- [ ] Login-Fehler Logging

### SERVICE-003: User Profile
**Kategorie:** service | **Komplexität:** medium
**Abhängig von:** SERVICE-002

- [ ] GET /api/users/me - Eigenes Profil
- [ ] PUT /api/users/me - Profil Update
- [ ] Avatar Upload
- [ ] Settings JSONB Update

---

## Phase 4: Security (Priority 2)

### SECURITY-001: Authentication Middleware
**Kategorie:** security | **Komplexität:** complex
**Abhängig von:** SERVICE-002

- [ ] JWT Verification Middleware
- [ ] User Context in Request
- [ ] Token Refresh Logik
- [ ] Logout mit Token Invalidierung

### SECURITY-002: Authorization (RBAC)
**Kategorie:** security | **Komplexität:** complex
**Abhängig von:** SECURITY-001

- [ ] Roles: admin, user, guest
- [ ] Permission Matrix definiert
- [ ] Authorization Middleware
- [ ] Row Level Security

### SECURITY-003: Input Validation
**Kategorie:** security | **Komplexität:** medium
**Abhängig von:** API-001

- [ ] Zod Schemas für alle Endpoints
- [ ] Request Body Validation
- [ ] Query Parameter Validation
- [ ] Sanitization gegen XSS

---

## Phase 5: API Endpoints (Priority 2-3)

### API-001: Main Entity CRUD
**Kategorie:** api | **Komplexität:** medium
**Abhängig von:** DATABASE-002, SERVICE-002

- [ ] GET /api/entities - Liste mit Pagination
- [ ] GET /api/entities/:id - Einzelnes Item
- [ ] POST /api/entities - Erstellen (Auth required)
- [ ] PUT /api/entities/:id - Update (Owner only)
- [ ] DELETE /api/entities/:id - Soft Delete

### API-002: Search & Filter
**Kategorie:** api | **Komplexität:** medium
**Abhängig von:** API-001

- [ ] Query Parameter: \`?q=search&status=active\`
- [ ] Sortierung: \`?sort=created_at&order=desc\`
- [ ] Pagination: \`?page=1&limit=20\`
- [ ] Response mit \`{ data, total, page, pages }\`

### API-003: API Documentation
**Kategorie:** api | **Komplexität:** simple
**Abhängig von:** API-001

- [ ] OpenAPI 3.0 Spec (swagger.json)
- [ ] Swagger UI auf /api/docs
- [ ] Request/Response Schemas
- [ ] Authentifizierung dokumentiert

---

## Phase 6: Frontend (Priority 3)

### UI-001: Layout & Navigation
**Kategorie:** ui | **Komplexität:** medium

- [ ] Root Layout mit Metadata
- [ ] Header mit Logo & Navigation
- [ ] Mobile-responsive Sidebar
- [ ] Footer mit Links
- [ ] Loading States

### UI-002: Auth Pages
**Kategorie:** ui | **Komplexität:** medium
**Abhängig von:** SERVICE-001, SERVICE-002

- [ ] /login - Login Form
- [ ] /register - Registration Form
- [ ] /forgot-password - Password Reset
- [ ] Form Validation mit Zod
- [ ] Error/Success Messages

### UI-003: Dashboard
**Kategorie:** ui | **Komplexität:** medium
**Abhängig von:** UI-001, API-001

- [ ] /dashboard - Übersichtsseite
- [ ] Stats Cards (KPIs)
- [ ] Recent Activity Liste
- [ ] Quick Action Buttons
- [ ] Skeleton Loading

### UI-004: Entity Management
**Kategorie:** ui | **Komplexität:** medium
**Abhängig von:** UI-003, API-001

- [ ] /entities - Liste mit Tabelle
- [ ] /entities/new - Create Form
- [ ] /entities/[id] - Detail View
- [ ] /entities/[id]/edit - Edit Form
- [ ] Delete Confirmation Modal

### UI-005: User Settings
**Kategorie:** ui | **Komplexität:** medium
**Abhängig von:** UI-002, SERVICE-003

- [ ] /settings - Settings Page
- [ ] Profile Edit Form
- [ ] Avatar Upload
- [ ] Password Change
- [ ] Theme Toggle (Dark/Light)

---

## Phase 7: Testing (Priority 4)

### TEST-001: Unit Tests Setup
**Kategorie:** test | **Komplexität:** simple

- [ ] Vitest Konfiguration
- [ ] Test Utils & Helpers
- [ ] Mock Factories
- [ ] Coverage Report Setup

### TEST-002: Service Tests
**Kategorie:** test | **Komplexität:** simple
**Abhängig von:** TEST-001, SERVICE-001

- [ ] Auth Service Tests
- [ ] Entity Service Tests
- [ ] Error Cases getestet
- [ ] Edge Cases getestet

### TEST-003: API Tests
**Kategorie:** test | **Komplexität:** medium
**Abhängig von:** TEST-001, API-001

- [ ] Supertest für HTTP Tests
- [ ] Auth Flow Tests
- [ ] CRUD Tests für alle Entities
- [ ] Error Response Tests

### TEST-004: E2E Tests
**Kategorie:** test | **Komplexität:** medium
**Abhängig von:** UI-002, UI-003

- [ ] Playwright Setup
- [ ] Login/Logout Flow
- [ ] CRUD Flow für Entity
- [ ] Error State Tests
- [ ] Mobile Viewport Tests

---

## Globale Akzeptanzkriterien

Das Projekt gilt als **fertig** wenn:

1. [ ] Alle Features in \`feature_list.json\` haben \`passes: true\`
2. [ ] \`npm run build\` erfolgreich (keine Errors)
3. [ ] \`npm run lint\` erfolgreich (keine Warnings)
4. [ ] \`npm run test\` alle Tests bestehen
5. [ ] TypeScript: keine Errors (\`tsc --noEmit\`)
6. [ ] Deployment auf ${input.techStack.hosting} funktioniert
7. [ ] Health-Check \`/api/health\` returns 200

---

## Changelog

| Datum | Änderung |
|-------|----------|
| ${new Date().toISOString().split('T')[0]} | Initial Spec generiert via eLuma Companion |

`;
};

function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export const LLM_EXPANSION_PROMPT = `Du bist ein erfahrener Software-Architekt. Deine Aufgabe ist es, aus einer Projekt-Idee eine vollständige Harness-Specification zu erstellen.

EINGABE:
- Projektname: {projectName}
- Problem: {problemStatement}
- Zielgruppe: {targetAudience}
- Lösung: {solution}
- Tech-Stack: {techStack}
- Hauptfeatures: {mainFeatures}
- Constraints: {constraints}
- Differenzierung: {differentiation}
- Risiken: {risks}

AUFGABE:
1. Expandiere die gegebenen Hauptfeatures in 40-60 detaillierte Features
2. Kategorisiere jedes Feature:
   - config: Setup, Konfiguration, Environment
   - database: Schema, Migrations, Queries
   - service: Business-Logik, Backend-Services
   - api: REST Endpoints, GraphQL
   - ui: Frontend-Komponenten, Pages
   - integration: Externe APIs, Webhooks
   - security: Auth, Authorization, Validation
   - test: Unit, Integration, E2E Tests
   - worker: Background Jobs, Queues
   - infrastructure: CI/CD, Monitoring, Deployment

3. Definiere Dependencies (linear, keine Zyklen!)
   - CONFIG-* hat keine Dependencies
   - DATABASE-* hängt von CONFIG-003 ab
   - SERVICE-* hängt von DATABASE-* ab
   - API-* hängt von SERVICE-* und DATABASE-* ab
   - UI-* hängt von API-* ab
   - usw.

4. Schätze Komplexität:
   - simple: 5-10 turns (Haiku)
   - medium: 10-25 turns (Sonnet)
   - complex: 25-50 turns (Opus)

5. Schreibe 3-5 konkrete Akzeptanzkriterien pro Feature

OUTPUT-FORMAT:
Gib die Features als JSON-Array zurück:
[
  {
    "id": "CONFIG-001",
    "title": "Project Setup",
    "category": "config",
    "complexity": "simple",
    "dependsOn": [],
    "acceptanceCriteria": [
      "package.json existiert mit allen Dependencies",
      "TypeScript kompiliert ohne Fehler",
      "ESLint läuft ohne Warnings"
    ]
  },
  ...
]

Wichtig:
- Mindestens 40 Features
- Maximal 60 Features
- Jede Kategorie sollte vertreten sein
- Dependencies müssen logisch sein (keine Zyklen!)
- Akzeptanzkriterien müssen testbar sein`;
